# Generated by Django 4.1.2 on 2022-10-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LW', models.CharField(max_length=300)),
                ('Artist', models.CharField(max_length=300)),
                ('SongTitle', models.CharField(max_length=300)),
                ('Label', models.CharField(max_length=300)),
            ],
        ),
    ]
