# Generated by Django 4.1.2 on 2022-10-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='TW',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='songs',
            name='LW',
            field=models.IntegerField(),
        ),
    ]
